"""
PreToolUse hook (Edit|Write): block manual edits to generated AI context files.

The files below are produced by tools/ai/generate_ai_context_files.py, so a
manual edit is lost on the next regeneration. Exit code 2 blocks the tool call
and sends stderr back to Claude. Standard library only (runs on any Python 3).
"""

import json
import os
import sys

GENERATED_FILES = {
    "AGENTS.md": "tools/ai/ai_context_header.md (contributor rules) or tools/ai/llms-base.txt (API reference)",
    ".github/copilot-instructions.md": "tools/ai/ai_context_header.md (contributor rules) or tools/ai/llms-base.txt (API reference)",
    "llms-full.txt": "tools/ai/llms-base.txt or skills/*/SKILL.md (and references/)",
    "docs/llms-full.txt": "tools/ai/llms-base.txt or skills/*/SKILL.md (and references/)",
    "docs/llms.txt": "llms.txt at the repository root",
}


def main():
    try:
        payload = json.load(sys.stdin)
    except ValueError:
        return 0

    file_path = (payload.get("tool_input") or {}).get("file_path")
    if not file_path:
        return 0

    project_dir = os.environ.get("CLAUDE_PROJECT_DIR") or payload.get("cwd") or os.getcwd()
    try:
        rel_path = os.path.relpath(os.path.abspath(file_path), os.path.abspath(project_dir))
    except ValueError:
        # Different drives on Windows: the file is outside the project.
        return 0
    rel_path = rel_path.replace(os.sep, "/")

    source = GENERATED_FILES.get(rel_path)
    if source is None:
        return 0

    sys.stderr.write(
        f"{rel_path} is generated by tools/ai/generate_ai_context_files.py and must "
        f"not be edited by hand. Edit {source} instead, then run "
        "`python tools/ai/generate_ai_context_files.py` and "
        "`python tools/ai/generate_ai_context_files.py --check`.\n"
    )
    return 2


if __name__ == "__main__":
    sys.exit(main())
