coverage:
  status:
    project:
      default:
        # Commits pushed to main should not make the overall
        # project coverage decrease by more than 1%:
        target: auto
        threshold: 1%
    patch:
      default:
        # Minimum coverage for all new code. If, for example
        target: auto
        target: 80%
