# Execute and save all documentation notebooks, collecting warnings
# ======================================================================================
# Usage:
#   python tools/docs/execute_notebooks/execute_notebooks.py                  # All docs/
#   python tools/docs/execute_notebooks/execute_notebooks.py user_guides      # Only docs/user_guides/
#   python tools/docs/execute_notebooks/execute_notebooks.py quick-start faq  # Multiple subdirs
#   python tools/docs/execute_notebooks/execute_notebooks.py user_guides/hyperparameter-tuning-and-lags-selection.ipynb
#   python tools/docs/execute_notebooks/execute_notebooks.py --include-slow   # Also run SLOW_NOTEBOOKS
#   python tools/docs/execute_notebooks/execute_notebooks.py --check          # Scan saved outputs, no execution
#
# After each notebook runs, its tqdm progress bar widgets are replaced with
# static progress bars (see static_widgets.py).
#
# With --check, the saved outputs of every notebook in scope (excluded and slow
# ones included) are scanned for error outputs, unexecuted code cells and
# warnings, without executing anything.
#
# Exit code: 0 if every notebook ran (or was scanned) without problems, warnings
# allowed; 1 if a notebook failed, needs review, or the run was interrupted.
# ======================================================================================
import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import logging
import importlib.metadata
from pathlib import Path
from datetime import datetime
import time

from static_widgets import convert_notebook

# On Windows the console defaults to a legacy code page (e.g. cp1252). The status
# glyphs (✓ ✗ ⚠) and the rich panels of the warnings would raise
# UnicodeEncodeError and abort the run mid-report. Force UTF-8 with replacement.
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass

REPO_ROOT = Path(__file__).resolve().parents[3]
DOCS_DIR = REPO_ROOT / "docs"
LOG_DIR = REPO_ROOT / "tools/docs/execute_notebooks/logs"
EXECUTION_TIMEOUT = 600  # Max seconds per cell before aborting the notebook (10 min)
KERNEL_NAME = "python3"  # Jupyter kernel used to execute every notebook

# Packages whose versions are reported in the header and summary.
# Key = display label, value = distribution name for importlib.metadata.version
REPORT_PACKAGES = {
    "skforecast":   "skforecast",
    "pandas":       "pandas",
    "numpy":        "numpy",
    "scikit-learn": "scikit-learn",
    "lightgbm":     "lightgbm",
    "keras":        "keras",
    "pytorch":      "torch",
}

# Skforecast custom warning categories (rendered as rich panels in notebooks).
# These are controlled warnings and are separated from external warnings in logs.
SKFORECAST_WARNING_CATEGORIES = {
    "DataTypeWarning",
    "DataTransformationWarning",
    "ExogenousInterpretationWarning",
    "FeatureOutOfRangeWarning",
    "IgnoredArgumentWarning",
    "InputTypeWarning",
    "LicenseWarning",
    "LongTrainingWarning",
    "MissingExogWarning",
    "MissingValuesWarning",
    "OneStepAheadValidationWarning",
    "ResidualsUsageWarning",
    "UnknownLevelWarning",
    "SaveLoadSkforecastWarning",
    "SkforecastVersionWarning",
}

# Notebooks to exclude (by name or relative path within docs/)
EXCLUDE_NOTEBOOKS = [
    "user_guides/forecasting-with-deep-learning-rnn-lstm.ipynb",
    "user_guides/foundation-forecasting-models.ipynb",  # Specific environment
    "user_guides/foundation-forecasting-with-heterogeneous-series.ipynb",  # Specific environment
    "user_guides/skforecast-in-GPU.ipynb",
    "user_guides/sktime-pipelines.ipynb",

    "faq/profiling-skforecast.ipynb",
    "faq/skforecast-benchmark.ipynb"
]

# Notebooks that take a long time to execute (by name or relative path within docs/).
# They are skipped when scanning directories unless ``--include-slow`` is passed.
# A slow notebook given explicitly as a file target is always executed.
SLOW_NOTEBOOKS = [
    "user_guides/feature-selection.ipynb",  # ~7 min
    "user_guides/probabilistic-forecasting-quantile-regression.ipynb",  # ~9 min
    "user_guides/stacking-ensemble-models-forecasting.ipynb",  # ~3 min

    "faq/parallelization-skforecast.ipynb",  # ~10 min
    "faq/parameters-search-backtesting-vs-one-step-ahead.ipynb",  # ~5 min
]

# Files generated by specific notebooks that should be cleaned up after execution.
# Paths are relative to the notebook's directory.
CLEANUP_FILES = {
    "user_guides/backtesting.ipynb": [
        "backtesting.gif",
    ],
    "user_guides/forecaster-in-production.ipynb": [
        "forecaster_001.joblib",
    ],
    "user_guides/hyperparameter-tuning-and-lags-selection.ipynb": [
        "results_grid_search.txt",
    ],
    "user_guides/save-load-forecaster.ipynb": [
        "forecaster_001.joblib",
        "forecaster_001.pkl",
        "forecaster_001.skops",
        "forecaster_custom_features.joblib",
        "forecaster_custom_features.cloudpickle",
        "forecaster_multiseries_custom_features.joblib",
        "custom_weights.py",
        "custom_weights_item_1.py",
        "custom_weights_item_2.py",
        "custom_weights_item_3.py",
    ]
}


# ANSI color codes
class C:
    HEADER = "\033[96m"
    OK     = "\033[92m"
    FAIL   = "\033[91m"
    INFO   = "\033[93m"
    END    = "\033[0m"


_ANSI_ESCAPE = re.compile(r'\033\[[0-9;]*m')


def _strip_ansi(text):
    return _ANSI_ESCAPE.sub('', text)


def _setup_logger(log_path):
    logger = logging.getLogger("docs_nb_runner")
    logger.setLevel(logging.DEBUG)
    logger.handlers.clear()
    logger.propagate = False  # Do not log twice through the root logger

    # Console handler: preserves ANSI colours
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter("%(message)s"))
    logger.addHandler(ch)

    # File handler: strips ANSI so the file is plain-text readable
    class _PlainFormatter(logging.Formatter):
        def format(self, record):
            return _strip_ansi(super().format(record))

    fh = logging.FileHandler(log_path, encoding="utf-8")
    fh.setLevel(logging.DEBUG)
    fh.setFormatter(_PlainFormatter("%(message)s"))
    logger.addHandler(fh)

    return logger


def _get_pkg_version(pkg):
    try:
        return importlib.metadata.version(pkg)
    except Exception:
        return "n/a"


def _log_versions(log):
    """Log the version of every package listed in REPORT_PACKAGES, aligned."""
    width = max(len(label) for label in REPORT_PACKAGES)
    for label, dist in REPORT_PACKAGES.items():
        log.info(f"{label:<{width}} : {_get_pkg_version(dist)}")


def _get_active_env():
    """Name of the Python environment running this script.

    Uses CONDA_DEFAULT_ENV when this interpreter belongs to the activated conda
    env, and falls back to the interpreter prefix basename (conda envs launched
    by their interpreter directly, plain virtualenvs).
    """
    conda_prefix = os.environ.get("CONDA_PREFIX")
    if conda_prefix and Path(conda_prefix).resolve() == Path(sys.prefix).resolve():
        return os.environ.get("CONDA_DEFAULT_ENV") or Path(sys.prefix).name
    return Path(sys.prefix).name


def _get_kernel_python(kernel_name):
    """Interpreter that a Jupyter kernel runs, or (None, reason) if unknown.

    jupyter_client replaces a bare 'python' in the kernelspec with the
    interpreter running this script, so that case resolves to sys.executable.
    """
    try:
        from jupyter_client.kernelspec import KernelSpecManager
        spec = KernelSpecManager().get_kernel_spec(kernel_name)
    except Exception as e:
        return None, f"n/a ({type(e).__name__})"

    exe = spec.argv[0] if spec.argv else ""
    major, minor = sys.version_info[:2]
    if exe in {"python", f"python{major}", f"python{major}.{minor}"}:
        return sys.executable, ""
    if not os.path.isabs(exe):
        exe = shutil.which(exe) or ""
    if exe and os.path.exists(exe):
        return exe, ""
    return None, f"n/a (kernelspec interpreter '{spec.argv[0]}' not found)"


def _get_kernel_skforecast(kernel_python):
    """Location of the skforecast package imported by the kernel interpreter.

    The kernel runs from the notebook's folder, where the repository is not on
    the path, so a regular (non-editable) install in site-packages silently
    shadows the repository code. Returns (location, is_repo_code).
    """
    try:
        proc = subprocess.run(
            [kernel_python, "-c", "import skforecast; print(skforecast.__file__)"],
            cwd=DOCS_DIR / "user_guides",
            capture_output=True,
            text=True,
            timeout=120,
        )
    except Exception as e:
        return f"n/a ({type(e).__name__})", False
    if proc.returncode != 0:
        last_line = (proc.stderr.strip().splitlines() or ["unknown error"])[-1]
        return f"n/a ({last_line})", False
    location = proc.stdout.strip()
    if location == "None":
        # Namespace package: a 'skforecast' folder without __init__.py, such as
        # the leftovers of an uninstalled version in site-packages
        return "n/a (folder without __init__.py, not an installed package)", False
    location = Path(location).resolve()
    return str(location), location.is_relative_to(REPO_ROOT / "skforecast")


def _warnings_from_text(text, external_warnings, skforecast_warnings):
    """Add the warnings found in the text of one output to the given counters.

    External entries combine the warning header line and the first non-empty
    message line, e.g. 'file:line: DeprecationWarning: | message text'.
    Skforecast entries are 'CategoryName: message summary'.
    """
    # Strip ANSI escape codes for clean parsing
    text = _strip_ansi(text)
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # Detect rich panel title (╭─── CategoryName ───╮)
        if stripped.startswith("╭"):
            category = None
            for cat in SKFORECAST_WARNING_CATEGORIES:
                if cat in stripped:
                    category = cat
                    break

            # Extract message from panel body lines (│ ... │)
            message_parts = []
            panel_category_from_body = None
            i += 1
            while i < len(lines) and not lines[i].strip().startswith("╰"):
                body = lines[i].strip().strip("│").strip()
                if body.startswith("Category"):
                    match = re.search(r'\.(\w+Warning)', body)
                    if match:
                        panel_category_from_body = match.group(1)
                elif body and not body.startswith(("Location", "Suppress")):
                    message_parts.append(body)
                i += 1
            i += 1  # skip ╰ line

            # Use title match first, then body match
            matched_category = category or panel_category_from_body

            # Skip panels that are not warnings at all
            if matched_category is None:
                continue

            entry = f"{matched_category}: {' '.join(message_parts)}" if message_parts else matched_category

            if matched_category in SKFORECAST_WARNING_CATEGORIES:
                skforecast_warnings[entry] = skforecast_warnings.get(entry, 0) + 1
            else:
                external_warnings[entry] = external_warnings.get(entry, 0) + 1
            continue

        # Skip lines that are part of a rich panel body (│ ... │)
        if stripped.startswith(("│", "╰")):
            i += 1
            continue

        # Standard Python / third-party warning
        if re.search(r'Warning', line):
            entry = stripped
            for next_line in lines[i + 1:i + 4]:
                ns = next_line.strip()
                if ns and not ns.startswith(("╭", "│", "╰")):
                    entry += " | " + ns
                    break
            external_warnings[entry] = external_warnings.get(entry, 0) + 1

        i += 1


def _scan_notebook(notebook_path):
    """Scan the saved outputs of a notebook for problems and warnings.

    Returns
    -------
    dict
        - errors: number of error outputs.
        - first_error: 'ename: evalue' of the first error output, or ''.
        - unexecuted: number of code cells with source but no execution_count
          (never run, so the published page is missing their outputs).
        - ext_warnings, skf_warnings: dict mapping warning text to its count,
          external (third-party libraries, Python) and skforecast custom ones.
        - scan_error: '' unless the notebook could not be read; it is then
          flagged for review instead of being reported as clean.
    """
    result = {
        "errors": 0,
        "first_error": "",
        "unexecuted": 0,
        "ext_warnings": {},
        "skf_warnings": {},
        "scan_error": "",
    }

    try:
        with open(notebook_path, encoding="utf-8") as fh:
            nb = json.load(fh)
    except Exception as e:
        result["scan_error"] = f"{type(e).__name__}: {e}"
        return result

    for cell in nb.get("cells", []):
        if cell.get("cell_type") != "code":
            continue

        source = cell.get("source", "")
        if isinstance(source, list):
            source = "".join(source)
        if source.strip() and cell.get("execution_count") is None:
            result["unexecuted"] += 1

        for output in cell.get("outputs", []):
            output_type = output.get("output_type")
            text = ""
            if output_type == "error":
                result["errors"] += 1
                if not result["first_error"]:
                    error = f"{output.get('ename', '')}: {output.get('evalue', '')}"
                    result["first_error"] = _strip_ansi(error).strip(": ")[:200]
                continue
            if output_type == "stream" and output.get("name") == "stderr":
                text = output.get("text", "")
            elif output_type in ("display_data", "execute_result"):
                text = output.get("data", {}).get("text/plain", "")
            if isinstance(text, list):
                text = "".join(text)
            if text:
                _warnings_from_text(
                    text, result["ext_warnings"], result["skf_warnings"]
                )

    return result


def _review_flags(scan):
    """Problems of a scanned notebook that need review, as short descriptions."""
    flags = []
    if scan["errors"]:
        flags.append(f"{scan['errors']} error output(s)")
    if scan["unexecuted"]:
        flags.append(f"{scan['unexecuted']} unexecuted cell(s)")
    if scan["scan_error"]:
        flags.append(f"could not scan outputs ({scan['scan_error']})")
    return flags


def _record_scan(results, notebook, scan):
    """Store the problems and warnings of a scanned notebook in ``results``."""
    if _review_flags(scan):
        results["needs_review"].append((notebook, scan))
    if scan["ext_warnings"] or scan["skf_warnings"]:
        results["warnings"].append((notebook, scan["ext_warnings"], scan["skf_warnings"]))


def _collect_notebooks(targets, include_slow=False, include_all=False):
    """Collect notebooks from the specified targets (subdirectories or files) of docs/.

    Notebooks listed in EXCLUDE_NOTEBOOKS are never collected from directory
    scans. Notebooks listed in SLOW_NOTEBOOKS are collected from directory scans
    only when ``include_slow`` is True. A notebook passed explicitly as a file
    target is always collected. With ``include_all`` (``--check``), excluded and
    slow notebooks are collected too.

    Returns
    -------
    tuple of (list[Path], list[Path])
        (notebooks, skipped_slow): notebooks to execute and slow notebooks that
        were skipped during directory scans.
    """

    exclude_set = {str(Path(x)) for x in EXCLUDE_NOTEBOOKS}
    slow_set = {str(Path(x)) for x in SLOW_NOTEBOOKS}

    notebooks = []
    skipped_slow = []
    search_dirs = []
    if targets:
        for target in targets:
            target_path = DOCS_DIR / target
            if target_path.is_file() and target_path.suffix == ".ipynb":
                # Direct notebook path
                notebooks.append(target_path)
            elif target_path.is_dir():
                search_dirs.append(target_path)
            else:
                print(f"Warning: docs/{target} is not a valid file or directory, skipping.")
    else:
        search_dirs = [DOCS_DIR]

    for search_dir in search_dirs:
        for nb in search_dir.rglob("*.ipynb"):
            # Skip checkpoints and partial outputs left by an in-progress or aborted run
            if ".ipynb_checkpoints" in str(nb) or nb.stem.endswith("_temp_exec"):
                continue
            if include_all:
                notebooks.append(nb)
                continue
            rel = str(nb.relative_to(DOCS_DIR))
            if nb.name in exclude_set or rel in exclude_set:
                continue
            if not include_slow and (nb.name in slow_set or rel in slow_set):
                skipped_slow.append(nb)
                continue
            notebooks.append(nb)

    return sorted(set(notebooks)), sorted(set(skipped_slow))


def _cleanup_generated_files(notebook, rel_path, log):
    """Remove files generated by a notebook execution, as listed in CLEANUP_FILES."""
    rel_key = str(rel_path)
    if rel_key not in CLEANUP_FILES:
        return
    for file_rel in CLEANUP_FILES[rel_key]:
        file_path = notebook.parent / file_rel
        if file_path.exists():
            file_path.unlink()
            log.info(f"  {C.INFO}Cleaned up:{C.END} {file_rel}")


def _safe_remove(path):
    """Remove a file if it exists, ignoring any error."""
    try:
        if os.path.exists(path):
            os.remove(path)
    except OSError:
        pass


def _log_warning_entries(log, warnings, indent="  ", label=True):
    """Log external warning entries, prefixed with their count when repeated."""
    tag = f"{C.INFO}WARNING:{C.END} " if label else ""
    for w, count in warnings.items():
        prefix = f"[{count}x] " if count > 1 else ""
        log.info(f"{indent}{tag}{prefix}{w}")


def _log_header(log, log_path, scope, notebooks, check):
    """Log the run configuration: environment, kernel and package versions."""
    log.info(f"Started    : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    log.info(f"Mode       : {'check saved outputs (no execution)' if check else 'execute'}")
    log.info(f"Log file   : {log_path.resolve()}")
    log.info(f"Directory  : {DOCS_DIR.resolve()}")
    log.info(f"Scope      : {scope}")
    log.info(f"Notebooks  : {len(notebooks)}")
    if check:
        return

    log.info(f"Env        : {_get_active_env()}")
    log.info(f"Interpreter: {sys.executable}")
    log.info(f"Python     : {sys.version.split()[0]}")
    log.info(f"papermill  : {_get_pkg_version('papermill')}")
    log.info(f"Kernel     : {KERNEL_NAME}")
    kernel_python, reason = _get_kernel_python(KERNEL_NAME)
    log.info(f"Kernel exe : {kernel_python or reason}")
    if kernel_python:
        location, is_repo_code = _get_kernel_skforecast(kernel_python)
        log.info(f"Kernel skf : {location}")
        if not is_repo_code:
            log.info(
                f"{C.FAIL}  WARNING: the kernel does not import skforecast from "
                f"this repository, notebooks will not run the repo code. Run "
                f"'pip install -e .' or set PYTHONPATH={REPO_ROOT}{C.END}"
            )
    _log_versions(log)
    log.info(f"Cell timeout: {EXECUTION_TIMEOUT} s")


def _check_notebooks(notebooks, results, log):
    """Scan the saved outputs of the notebooks without executing them."""
    log.info("")
    for notebook in notebooks:
        rel_path = notebook.relative_to(DOCS_DIR)
        scan = _scan_notebook(notebook)
        _record_scan(results, notebook, scan)
        flags = _review_flags(scan)
        if flags:
            line = f"{C.FAIL}⚠ {rel_path}{C.END}: {', '.join(flags)}"
        else:
            line = f"{C.OK}✓ {rel_path}{C.END}"
        if scan["first_error"]:
            line += f" | {scan['first_error']}"
        log.info(line)
        _log_warning_entries(log, scan["ext_warnings"], indent="    ")


def _execute_notebooks(notebooks, results, log):
    """Execute the notebooks in place, one by one.

    Returns the notebook being executed when the run was interrupted with
    Ctrl+C, or None.
    """
    # Imported here so that --check works without papermill installed
    import papermill as pm

    for i, notebook in enumerate(notebooks, 1):

        nb_start_time = datetime.now().strftime("%H:%M:%S")
        rel_path = notebook.relative_to(DOCS_DIR)
        log.info(f"\n{C.HEADER}{'=' * 60}")
        log.info(f"[{i}/{len(notebooks)}] {nb_start_time} | {C.INFO}{rel_path}{C.END}")
        log.info(f"{'=' * 60}{C.END}")

        temp_output_path = notebook.with_name(f"{notebook.stem}_temp_exec{notebook.suffix}")
        start = time.time()

        try:
            # log_output stays off: papermill would echo the raw cell outputs
            # through its own logger, which does not reach the run log; the
            # warnings are recovered from the saved notebook instead.
            pm.execute_notebook(
                input_path=str(notebook),
                output_path=temp_output_path,
                kernel_name=KERNEL_NAME,
                cwd=str(notebook.parent),
                progress_bar=False,
                log_output=False,
                execution_timeout=EXECUTION_TIMEOUT
            )
            elapsed = time.time() - start

            # Atomically replace the original with the successfully executed file
            try:
                os.replace(temp_output_path, str(notebook))
            except OSError as replace_err:
                _safe_remove(temp_output_path)
                _cleanup_generated_files(notebook, rel_path, log)
                msg = f"Could not save executed notebook: {replace_err}"
                results["failed"].append((notebook, elapsed, msg, {}, {}))
                log.info(f"{C.FAIL}✗ FAILED:{C.END} {rel_path} ({elapsed:.2f}s)")
                log.info(f"  {C.FAIL}Error:{C.END} {msg}")
                continue

            # Progress bar widgets (tqdm) to static bars, see static_widgets.py
            n_converted, n_removed = convert_notebook(notebook)
            if n_converted or n_removed:
                log.info(
                    f"  {C.INFO}Static progress bars:{C.END} {n_converted} "
                    f"converted, {n_removed} removed"
                )

            # Scan the saved notebook for warnings, error outputs and unexecuted cells
            scan = _scan_notebook(notebook)
            results["success"].append((notebook, elapsed))
            _record_scan(results, notebook, scan)
            ext_warnings, skf_warnings = scan["ext_warnings"], scan["skf_warnings"]

            parts = [f"{C.FAIL}{flag}{C.END}" for flag in _review_flags(scan)]
            if ext_warnings:
                parts.append(f"{C.INFO}{sum(ext_warnings.values())} warning(s){C.END}")
            if skf_warnings:
                parts.append(
                    f"{C.INFO}{sum(skf_warnings.values())} skforecast warning(s){C.END}"
                )
            _log_warning_entries(log, ext_warnings)
            if skf_warnings:
                log.info(
                    f"  {C.INFO}({sum(skf_warnings.values())} skforecast "
                    f"warnings suppressed){C.END}"
                )
            if scan["first_error"]:
                log.info(f"  {C.FAIL}First error output:{C.END} {scan['first_error']}")
            summary = f"{C.OK}✓ Success:{C.END} {rel_path} ({elapsed:.2f}s)"
            if parts:
                summary += " | " + ", ".join(parts)
            log.info(summary)

            # Clean up files generated by the notebook
            _cleanup_generated_files(notebook, rel_path, log)

        except Exception as e:
            elapsed = time.time() - start

            # Extract warnings from partial output before removing the temp file
            # (papermill writes the output file even on failure, up to the failing cell)
            if os.path.exists(temp_output_path):
                partial = _scan_notebook(temp_output_path)
                ext_partial, skf_partial = partial["ext_warnings"], partial["skf_warnings"]
            else:
                ext_partial, skf_partial = {}, {}
            _safe_remove(temp_output_path)

            # Clean up files generated by the notebook (even on failure)
            _cleanup_generated_files(notebook, rel_path, log)

            full_error = str(e)
            results["failed"].append((notebook, elapsed, full_error, ext_partial, skf_partial))
            if ext_partial or skf_partial:
                n_total = sum(ext_partial.values()) + sum(skf_partial.values())
                log.info(f"  {C.INFO}Warnings before failure ({n_total}):{C.END}")
                _log_warning_entries(log, ext_partial, indent="    ")
                if skf_partial:
                    log.info(f"    {C.INFO}({sum(skf_partial.values())} skforecast warnings suppressed){C.END}")
            log.info(f"{C.FAIL}✗ FAILED:{C.END} {rel_path} ({elapsed:.2f}s)")
            log.info(f"  {C.FAIL}Error:{C.END}\n{full_error}")

        except KeyboardInterrupt:
            elapsed = time.time() - start
            # Remove the partial output so the original notebook is left untouched
            _safe_remove(temp_output_path)
            _cleanup_generated_files(notebook, rel_path, log)
            log.info(
                f"{C.FAIL}✗ INTERRUPTED:{C.END} {rel_path} ({elapsed:.2f}s) | "
                f"{len(notebooks) - i} notebook(s) not executed"
            )
            return notebook

    return None


def run_notebooks(targets=None, include_slow=False, check=False):
    """Execute (or, with ``check``, only scan) the notebooks.

    Returns the process exit code: 0 if every notebook ran or was scanned
    without problems (warnings allowed), 1 if a notebook failed, needs review,
    no notebook was found or the run was interrupted.
    """

    timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
    if targets:
        suffix_parts = [t.replace("/", "_").replace(".ipynb", "") for t in targets]
        suffix = f"_{'_'.join(suffix_parts)}"
    else:
        suffix = ""
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    log_name = "docs_check_log" if check else "docs_execution_log"
    log_path = LOG_DIR / f"{log_name}{suffix}_{timestamp}.txt"
    log = _setup_logger(log_path)

    notebooks, skipped_slow = _collect_notebooks(
        targets, include_slow=include_slow, include_all=check
    )

    if not notebooks:
        log.info(f"{C.FAIL}No notebooks found.{C.END}")
        return 1

    # Partial outputs left by a run that was killed (not interrupted with Ctrl+C,
    # which removes them). MkDocs would publish them as pages.
    stale_temps = sorted(DOCS_DIR.rglob("*_temp_exec.ipynb"))
    if not check:
        for temp in stale_temps:
            _safe_remove(temp)

    results = {"success": [], "failed": [], "warnings": [], "needs_review": []}
    interrupted = None

    # ── Header ───────────────────────────────────────────────────────────────
    scope = ", ".join(f"docs/{t}" for t in targets) if targets else "docs/"
    _log_header(log, log_path, scope, notebooks, check)
    if not check:
        log.info(f"Slow       : {'included (--include-slow)' if include_slow else 'skipped'}")

    if stale_temps:
        action = "Removed" if not check else "Found"
        color = C.INFO if not check else C.FAIL
        log.info(
            f"\n{color}{action} {len(stale_temps)} partial output(s) of a previous "
            f"run:{C.END}"
        )
        for temp in stale_temps:
            log.info(f"  - {temp.relative_to(DOCS_DIR)}")

    if not check:
        if EXCLUDE_NOTEBOOKS:
            log.info(f"\n{C.INFO}Excluded notebooks:{C.END}")
            for exc in EXCLUDE_NOTEBOOKS:
                log.info(f"  - {exc}")

        if skipped_slow:
            log.info(f"\n{C.INFO}Skipped slow notebooks (run with --include-slow):{C.END}")
            for nb in skipped_slow:
                log.info(f"  - {nb.relative_to(DOCS_DIR)}")

    if SKFORECAST_WARNING_CATEGORIES:
        log.info(f"\n{C.INFO}Suppressed skforecast warning categories:{C.END}")
        for cat in sorted(SKFORECAST_WARNING_CATEGORIES):
            log.info(f"  - {cat}")

    total_start = time.time()

    # ── Execution / check loop ───────────────────────────────────────────────
    if check:
        _check_notebooks(notebooks, results, log)
    else:
        interrupted = _execute_notebooks(notebooks, results, log)

    total_elapsed = time.time() - total_start

    # ── Summary ──────────────────────────────────────────────────────────────
    log.info(f"\n{C.HEADER}{'=' * 60}")
    log.info("CHECK SUMMARY" if check else "EXECUTION SUMMARY")
    log.info(f"{'=' * 60}{C.END}")
    log.info(f"Finished     : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    log.info(f"Total time   : {total_elapsed:.1f}s ({total_elapsed / 60:.1f} min)")
    log.info(f"Scope        : {scope}")
    log.info(f"Total        : {C.INFO}{len(notebooks)}{C.END}")
    if check:
        log.info(f"Clean        : {C.OK}{len(notebooks) - len(results['needs_review'])}{C.END}")
    else:
        log.info(f"Excluded     : {C.INFO}{len(EXCLUDE_NOTEBOOKS)}{C.END}")
        log.info(f"Skipped slow : {C.INFO}{len(skipped_slow)}{C.END}")
        log.info(f"Successful   : {C.OK}{len(results['success'])}{C.END}")
        log.info(f"Failed       : {C.FAIL}{len(results['failed'])}{C.END}")
    log.info(f"Needs review : {C.FAIL}{len(results['needs_review'])}{C.END}")
    log.info(f"With warnings: {C.INFO}{len(results['warnings'])}{C.END}")
    if interrupted is not None:
        log.info(f"Interrupted  : {C.FAIL}{interrupted.relative_to(DOCS_DIR)}{C.END}")

    if not check:
        log.info(f"\n{C.INFO}Package versions:{C.END}")
        _log_versions(log)

    if results["failed"]:
        log.info(f"\n{C.FAIL}Failed notebooks:{C.END}")
        for nb, elapsed, _, ext_pw, skf_pw in results["failed"]:
            n_pw = sum(ext_pw.values()) + sum(skf_pw.values())
            suffix = f" | {n_pw} warning(s) before failure" if n_pw else ""
            log.info(f"  {C.FAIL}✗ {nb.relative_to(DOCS_DIR)}{C.END} ({elapsed:.2f}s){suffix}")
        log.info(f"\n{C.FAIL}Errors (full):{C.END}")
        for nb, elapsed, err, _, _ in results["failed"]:
            log.info(f"\n  {C.FAIL}── {nb.relative_to(DOCS_DIR)} ──{C.END}")
            log.info(err)

    if results["needs_review"]:
        log.info(
            f"\n{C.FAIL}Needs review (error outputs, unexecuted cells or failed "
            f"scan):{C.END}"
        )
        for nb, scan in results["needs_review"]:
            line = f"  {C.FAIL}⚠ {nb.relative_to(DOCS_DIR)}{C.END}: {', '.join(_review_flags(scan))}"
            if scan["first_error"]:
                line += f" | {scan['first_error']}"
            log.info(line)

    if results["warnings"]:
        log.info(f"\n{C.INFO}Notebooks with warnings:{C.END}")
        for nb, ext_warns, skf_warns in results["warnings"]:
            parts = []
            if ext_warns:
                parts.append(f"{sum(ext_warns.values())} warning(s)")
            if skf_warns:
                parts.append(f"{sum(skf_warns.values())} skforecast")
            log.info(f"  {C.INFO}⚠ {nb.relative_to(DOCS_DIR)}{C.END} ({', '.join(parts)})")
            _log_warning_entries(log, ext_warns, indent="    ", label=False)

        # Aggregate all skforecast warnings across notebooks
        all_skf = {}
        for _, _, skf_warns in results["warnings"]:
            for w, count in skf_warns.items():
                cat = w.split(":")[0]
                all_skf[cat] = all_skf.get(cat, 0) + count
        if all_skf:
            log.info(f"\n{C.INFO}Skforecast warnings summary (suppressed from per-notebook logs):{C.END}")
            for cat, count in sorted(all_skf.items(), key=lambda x: -x[1]):
                log.info(f"  {cat}: {count}")

        # Aggregate all external warnings across notebooks
        all_ext = {}
        for _, ext_warns, _ in results["warnings"]:
            for w, count in ext_warns.items():
                all_ext[w] = all_ext.get(w, 0) + count
        if all_ext:
            log.info(f"\n{C.INFO}External warnings summary (count across all notebooks):{C.END}")
            for w, count in sorted(all_ext.items(), key=lambda x: -x[1]):
                log.info(f"  [{count}x] {w}")

    log.info(f"\nFull log saved to: {log_path.resolve()}")

    problems = (
        results["failed"]
        or results["needs_review"]
        or interrupted is not None
        or (check and stale_temps)
    )
    return 1 if problems else 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Execute documentation notebooks and collect warnings.",
        epilog=(
            "Examples:\n"
            "  python tools/docs/execute_notebooks/execute_notebooks.py                  # All docs/\n"
            "  python tools/docs/execute_notebooks/execute_notebooks.py user_guides      # Only docs/user_guides/\n"
            "  python tools/docs/execute_notebooks/execute_notebooks.py quick-start faq  # Multiple subdirs\n"
            "  python tools/docs/execute_notebooks/execute_notebooks.py user_guides/hyperparameter-tuning-and-lags-selection.ipynb\n"
            "  python tools/docs/execute_notebooks/execute_notebooks.py --include-slow   # Also run SLOW_NOTEBOOKS\n"
            "  python tools/docs/execute_notebooks/execute_notebooks.py --check          # Scan saved outputs, no execution\n"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "targets",
        nargs="*",
        default=None,
        help="Subdirectories or notebook files (relative to docs/) to execute. "
             "Examples: 'user_guides', 'user_guides/backtesting.ipynb'. "
             "If omitted, all notebooks under docs/ are executed.",
    )
    parser.add_argument(
        "--include-slow",
        action="store_true",
        help="Also execute the notebooks listed in SLOW_NOTEBOOKS, which are "
             "skipped by default when scanning directories. A slow notebook "
             "passed explicitly as a file target is always executed.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not execute anything: scan the saved outputs of every notebook "
             "in scope (excluded and slow ones included) for error outputs, "
             "unexecuted code cells and warnings. Exit code 1 if any notebook "
             "has errors or unexecuted cells.",
    )
    args = parser.parse_args()
    sys.exit(
        run_notebooks(
            targets=args.targets or None,
            include_slow=args.include_slow,
            check=args.check,
        )
    )
