# Execute and save all documentation notebooks, collecting warnings
# ======================================================================================
# Usage:
#   python tools/execute_docs/execute_docs_notebooks.py                  # All docs/
#   python tools/execute_docs/execute_docs_notebooks.py user_guides      # Only docs/user_guides/
#   python tools/execute_docs/execute_docs_notebooks.py quick-start faq  # Multiple subdirs
#   python tools/execute_docs/execute_docs_notebooks.py user_guides/hyperparameter-tuning-and-lags-selection.ipynb
# ======================================================================================
import argparse
import papermill as pm
import nbformat
import os
import re
import sys
import logging
import importlib.metadata
from pathlib import Path
from datetime import datetime
import time

CONDA_ENV = "skforecast_py14"
REPO_ROOT = Path(__file__).resolve().parent.parent.parent
DOCS_DIR = REPO_ROOT / "docs"
LOG_DIR = REPO_ROOT / "tools/execute_docs/logs"
EXECUTION_TIMEOUT = 600  # Max seconds per cell before aborting the notebook (10 min)

# Skforecast custom warning categories (rendered as rich panels in notebooks).
# These are controlled warnings and are separated from external warnings in logs.
SKFORECAST_WARNING_CATEGORIES = {
    "DataTypeWarning", 
    "DataTransformationWarning", 
    "ExogenousInterpretationWarning",
    "FeatureOutOfRangeWarning", 
    "IgnoredArgumentWarning", 
    "InputTypeWarning",
    "LongTrainingWarning", 
    "MissingExogWarning", 
    "MissingValuesWarning",
    "OneStepAheadValidationWarning", 
    "ResidualsUsageWarning", 
    "UnknownLevelWarning",
    "SaveLoadSkforecastWarning", 
    "SkforecastVersionWarning",
}

# Notebooks to exclude (by name or relative path within docs/)
EXCLUDE_NOTEBOOKS = [
    "user_guides/feature-selection.ipynb",  # Too long
    "user_guides/forecasting-with-deep-learning-rnn-lstm.ipynb", 
    "user_guides/foundation-forecasting-models.ipynb",  # Specific environment
    "user_guides/skforecast-in-GPU.ipynb",
    "user_guides/sktime-pipelines.ipynb",

    "faq/profiling-skforecast.ipynb",
    "faq/skforecast-benchmark.ipynb"
]

# Files generated by specific notebooks that should be cleaned up after execution.
# Paths are relative to the notebook's directory.
CLEANUP_FILES = {
    "user_guides/backtesting.ipynb": [
        "backtesting.gif",
    ],
    "user_guides/forecaster-in-production.ipynb": [
        "forecaster_001.joblib",
    ],
    "user_guides/hyperparameter-tuning-and-lags-selection.ipynb": [
        "results_grid_search.txt",
    ],
    "user_guides/save-load-forecaster.ipynb": [
        "forecaster_001.joblib",
        "forecaster_custom_features.joblib",
        "forecaster_multiseries_custom_features.joblib",
        "custom_weights.py",
        "custom_weights_item_1.py",
        "custom_weights_item_2.py",
        "custom_weights_item_3.py",
    ]
}


# ANSI color codes
class C:
    HEADER = "\033[96m"
    OK     = "\033[92m"
    FAIL   = "\033[91m"
    INFO   = "\033[93m"
    END    = "\033[0m"


_ANSI_ESCAPE = re.compile(r'\033\[[0-9;]*m')


def _strip_ansi(text):
    return _ANSI_ESCAPE.sub('', text)


def _setup_logger(log_path):
    logger = logging.getLogger("docs_nb_runner")
    logger.setLevel(logging.DEBUG)
    logger.handlers.clear()

    # Console handler — preserves ANSI colours
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter("%(message)s"))
    logger.addHandler(ch)

    # File handler — strips ANSI so the file is plain-text readable
    class _PlainFormatter(logging.Formatter):
        def format(self, record):
            return _strip_ansi(super().format(record))

    fh = logging.FileHandler(log_path, encoding="utf-8")
    fh.setLevel(logging.DEBUG)
    fh.setFormatter(_PlainFormatter("%(message)s"))
    logger.addHandler(fh)

    return logger


def _get_pkg_version(pkg):
    try:
        return importlib.metadata.version(pkg)
    except Exception:
        return "n/a"


def _extract_warnings(notebook_path):
    """Parse a notebook file and return warning entries with counts from cell outputs.

    Separates external warnings (third-party libraries, Python) from skforecast
    custom warnings (rendered as rich panels in notebooks).

    Returns
    -------
    tuple of (dict[str, int], dict[str, int])
        (external_warnings, skforecast_warnings).
        Each dict maps warning text to its occurrence count.
        External entries combine the warning header line and the first non-empty
        message line, e.g. 'file:line: DeprecationWarning: — message text'.
        Skforecast entries are 'CategoryName: message summary'.
    """
    external_warnings = {}
    skforecast_warnings = {}

    try:
        nb = nbformat.read(notebook_path, as_version=4)
        for cell in nb.cells:
            for output in cell.get("outputs", []):
                text = ""
                if output.get("output_type") == "stream" and output.get("name") == "stderr":
                    text = "".join(output.get("text", []))
                elif output.get("output_type") in ("display_data", "execute_result"):
                    text = "".join(output.get("data", {}).get("text/plain", []))
                if not text:
                    continue

                # Strip ANSI escape codes for clean parsing
                text = _strip_ansi(text)
                lines = text.splitlines()
                i = 0
                while i < len(lines):
                    line = lines[i]
                    stripped = line.strip()

                    # Detect rich panel title (╭─── CategoryName ───╮)
                    if stripped.startswith("╭"):
                        category = None
                        for cat in SKFORECAST_WARNING_CATEGORIES:
                            if cat in stripped:
                                category = cat
                                break

                        # Extract message from panel body lines (│ ... │)
                        message_parts = []
                        panel_category_from_body = None
                        i += 1
                        while i < len(lines) and not lines[i].strip().startswith("╰"):
                            body = lines[i].strip().strip("│").strip()
                            if body.startswith("Category"):
                                match = re.search(r'\.(\w+Warning)', body)
                                if match:
                                    panel_category_from_body = match.group(1)
                            elif body and not body.startswith(("Location", "Suppress")):
                                message_parts.append(body)
                            i += 1
                        i += 1  # skip ╰ line

                        # Use title match first, then body match
                        matched_category = category or panel_category_from_body

                        # Skip panels that are not warnings at all
                        if matched_category is None:
                            continue

                        entry = f"{matched_category}: {' '.join(message_parts)}" if message_parts else matched_category

                        if matched_category in SKFORECAST_WARNING_CATEGORIES:
                            skforecast_warnings[entry] = skforecast_warnings.get(entry, 0) + 1
                        else:
                            external_warnings[entry] = external_warnings.get(entry, 0) + 1
                        continue

                    # Skip lines that are part of a rich panel body (│ ... │)
                    if stripped.startswith(("│", "╰")):
                        i += 1
                        continue

                    # Standard Python / third-party warning
                    if re.search(r'Warning', line):
                        entry = stripped
                        for next_line in lines[i + 1:i + 4]:
                            ns = next_line.strip()
                            if ns and not ns.startswith(("╭", "│", "╰")):
                                entry += " — " + ns
                                break
                        external_warnings[entry] = external_warnings.get(entry, 0) + 1

                    i += 1

    except Exception:
        pass

    return external_warnings, skforecast_warnings


def _collect_notebooks(targets):
    """Collect notebooks from the specified targets (subdirectories or files) of docs/."""

    exclude_set = {str(Path(x)) for x in EXCLUDE_NOTEBOOKS}

    if targets:
        notebooks = []
        search_dirs = []
        for target in targets:
            target_path = DOCS_DIR / target
            if target_path.is_file() and target_path.suffix == ".ipynb":
                # Direct notebook path
                notebooks.append(target_path)
            elif target_path.is_dir():
                search_dirs.append(target_path)
            else:
                print(f"Warning: docs/{target} is not a valid file or directory, skipping.")
    else:
        notebooks = []
        search_dirs = [DOCS_DIR]

    for search_dir in search_dirs:
        notebooks.extend([
            nb for nb in search_dir.rglob("*.ipynb")
            if ".ipynb_checkpoints" not in str(nb)
            and (nb.name not in exclude_set)
            and (str(nb.relative_to(DOCS_DIR)) not in exclude_set)
        ])

    return sorted(set(notebooks))


def _cleanup_generated_files(notebook, rel_path, log):
    """Remove files generated by a notebook execution, as listed in CLEANUP_FILES."""
    rel_key = str(rel_path)
    if rel_key not in CLEANUP_FILES:
        return
    for file_rel in CLEANUP_FILES[rel_key]:
        file_path = notebook.parent / file_rel
        if file_path.exists():
            file_path.unlink()
            log.info(f"  {C.INFO}Cleaned up:{C.END} {file_rel}")


def run_notebooks(targets=None):

    timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
    if targets:
        suffix_parts = [t.replace("/", "_").replace(".ipynb", "") for t in targets]
        suffix = f"_{'_'.join(suffix_parts)}"
    else:
        suffix = ""
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    log_path  = LOG_DIR / f"docs_execution_log{suffix}_{timestamp}.txt"
    log = _setup_logger(log_path)

    notebooks = _collect_notebooks(targets)

    if not notebooks:
        log.info(f"{C.FAIL}No notebooks found.{C.END}")
        return

    results = {"success": [], "failed": [], "warnings": []}

    # ── Header ───────────────────────────────────────────────────────────────
    scope = ", ".join(f"docs/{t}" for t in targets) if targets else "docs/"
    log.info(f"Started    : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    log.info(f"Log file   : {log_path.resolve()}")
    log.info(f"Directory  : {DOCS_DIR.resolve()}")
    log.info(f"Scope      : {scope}")
    log.info(f"Env        : {CONDA_ENV}")
    log.info("Kernel     : python3")
    log.info(f"Python     : {sys.version.split()[0]}")
    log.info(f"papermill  : {_get_pkg_version('papermill')}")
    log.info(f"skforecast : {_get_pkg_version('skforecast')}")
    log.info(f"Notebooks  : {len(notebooks)}")

    if EXCLUDE_NOTEBOOKS:
        log.info(f"\n{C.INFO}Excluded notebooks:{C.END}")
        for exc in EXCLUDE_NOTEBOOKS:
            log.info(f"  - {exc}")

    if SKFORECAST_WARNING_CATEGORIES:
        log.info(f"\n{C.INFO}Suppressed skforecast warning categories:{C.END}")
        for cat in sorted(SKFORECAST_WARNING_CATEGORIES):
            log.info(f"  - {cat}")

    total_start = time.time()

    # ── Execution loop ────────────────────────────────────────────────────────
    for i, notebook in enumerate(notebooks, 1):

        nb_start_time = datetime.now().strftime("%H:%M:%S")
        rel_path = notebook.relative_to(DOCS_DIR)
        log.info(f"\n{C.HEADER}{'=' * 60}")
        log.info(f"[{i}/{len(notebooks)}] {nb_start_time} — {C.INFO}{rel_path}{C.END}")
        log.info(f"{'=' * 60}{C.END}")

        temp_output_path = notebook.with_name(f"{notebook.stem}_temp_exec{notebook.suffix}")
        start = time.time()

        try:
            pm.execute_notebook(
                input_path=str(notebook),
                output_path=temp_output_path,
                kernel_name='python3',
                cwd=str(notebook.parent),
                progress_bar=False,
                log_output=True,
                execution_timeout=EXECUTION_TIMEOUT
            )
            elapsed = time.time() - start

            # Atomically replace the original with the successfully executed file
            os.replace(temp_output_path, str(notebook))

            # Extract warnings from the saved notebook outputs
            ext_warnings, skf_warnings = _extract_warnings(notebook)
            results["success"].append((notebook, elapsed))

            n_ext = sum(ext_warnings.values())
            n_skf = sum(skf_warnings.values())

            if ext_warnings or skf_warnings:
                results["warnings"].append((notebook, ext_warnings, skf_warnings))
                parts = []
                if ext_warnings:
                    parts.append(f"{n_ext} warning(s)")
                if skf_warnings:
                    parts.append(f"{n_skf} skforecast warning(s)")
                for w, count in ext_warnings.items():
                    prefix = f"[{count}x] " if count > 1 else ""
                    log.info(f"  {C.INFO}WARNING:{C.END} {prefix}{w}")
                if skf_warnings:
                    log.info(f"  {C.INFO}({n_skf} skforecast warnings suppressed){C.END}")
                log.info(
                    f"{C.OK}✓ Success:{C.END} {rel_path} ({elapsed:.2f}s) | "
                    f"{C.INFO}{', '.join(parts)}{C.END}"
                )
            else:
                log.info(f"{C.OK}✓ Success:{C.END} {rel_path} ({elapsed:.2f}s)")

            # Clean up files generated by the notebook
            _cleanup_generated_files(notebook, rel_path, log)

        except Exception as e:
            elapsed = time.time() - start

            # Extract warnings from partial output before removing the temp file
            # (papermill writes the output file even on failure, up to the failing cell)
            ext_partial, skf_partial = (
                _extract_warnings(temp_output_path)
                if os.path.exists(temp_output_path) else ({}, {})
            )
            if os.path.exists(temp_output_path):
                os.remove(temp_output_path)

            # Clean up files generated by the notebook (even on failure)
            _cleanup_generated_files(notebook, rel_path, log)

            full_error = str(e)
            results["failed"].append((notebook, elapsed, full_error, ext_partial, skf_partial))
            if ext_partial or skf_partial:
                n_total = sum(ext_partial.values()) + sum(skf_partial.values())
                log.info(f"  {C.INFO}Warnings before failure ({n_total}):{C.END}")
                for w, count in ext_partial.items():
                    prefix = f"[{count}x] " if count > 1 else ""
                    log.info(f"    {C.INFO}WARNING:{C.END} {prefix}{w}")
                if skf_partial:
                    log.info(f"    {C.INFO}({sum(skf_partial.values())} skforecast warnings suppressed){C.END}")
            log.info(f"{C.FAIL}✗ FAILED:{C.END} {rel_path} ({elapsed:.2f}s)")
            log.info(f"  {C.FAIL}Error:{C.END}\n{full_error}")

    total_elapsed = time.time() - total_start

    # ── Summary ──────────────────────────────────────────────────────────────
    log.info(f"\n{C.HEADER}{'=' * 60}")
    log.info("EXECUTION SUMMARY")
    log.info(f"{'=' * 60}{C.END}")
    log.info(f"Finished     : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    log.info(f"Total time   : {total_elapsed:.1f}s ({total_elapsed / 60:.1f} min)")
    log.info(f"Scope        : {scope}")
    log.info(f"Total        : {C.INFO}{len(notebooks)}{C.END}")
    log.info(f"Excluded     : {C.INFO}{len(EXCLUDE_NOTEBOOKS)}{C.END}")
    log.info(f"Successful   : {C.OK}{len(results['success'])}{C.END}")
    log.info(f"Failed       : {C.FAIL}{len(results['failed'])}{C.END}")
    log.info(f"With warnings: {C.INFO}{len(results['warnings'])}{C.END}")

    if results["failed"]:
        log.info(f"\n{C.FAIL}Failed notebooks:{C.END}")
        for nb, elapsed, _, ext_pw, skf_pw in results["failed"]:
            n_pw = sum(ext_pw.values()) + sum(skf_pw.values())
            suffix = f" | {n_pw} warning(s) before failure" if n_pw else ""
            log.info(f"  {C.FAIL}✗ {nb.relative_to(DOCS_DIR)}{C.END} ({elapsed:.2f}s){suffix}")
        log.info(f"\n{C.FAIL}Errors (full):{C.END}")
        for nb, elapsed, err, _, _ in results["failed"]:
            log.info(f"\n  {C.FAIL}── {nb.relative_to(DOCS_DIR)} ──{C.END}")
            log.info(err)

    if results["warnings"]:
        log.info(f"\n{C.INFO}Notebooks with warnings:{C.END}")
        for nb, ext_warns, skf_warns in results["warnings"]:
            parts = []
            if ext_warns:
                parts.append(f"{sum(ext_warns.values())} warning(s)")
            if skf_warns:
                parts.append(f"{sum(skf_warns.values())} skforecast")
            log.info(f"  {C.INFO}⚠ {nb.relative_to(DOCS_DIR)}{C.END} ({', '.join(parts)})")
            for w, count in ext_warns.items():
                prefix = f"[{count}x] " if count > 1 else ""
                log.info(f"    {prefix}{w}")

        # Aggregate all skforecast warnings across notebooks
        all_skf = {}
        for _, _, skf_warns in results["warnings"]:
            for w, count in skf_warns.items():
                cat = w.split(":")[0]
                all_skf[cat] = all_skf.get(cat, 0) + count
        if all_skf:
            log.info(f"\n{C.INFO}Skforecast warnings summary (suppressed from per-notebook logs):{C.END}")
            for cat, count in sorted(all_skf.items(), key=lambda x: -x[1]):
                log.info(f"  {cat}: {count}")

        # Aggregate all external warnings across notebooks
        all_ext = {}
        for _, ext_warns, _ in results["warnings"]:
            for w, count in ext_warns.items():
                all_ext[w] = all_ext.get(w, 0) + count
        if all_ext:
            log.info(f"\n{C.INFO}External warnings summary (count across all notebooks):{C.END}")
            for w, count in sorted(all_ext.items(), key=lambda x: -x[1]):
                log.info(f"  [{count}x] {w}")

    log.info(f"\nFull log saved to: {log_path.resolve()}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Execute documentation notebooks and collect warnings.",
        epilog=(
            "Examples:\n"
            "  python tools/execute_docs/execute_docs_notebooks.py                  # All docs/\n"
            "  python tools/execute_docs/execute_docs_notebooks.py user_guides      # Only docs/user_guides/\n"
            "  python tools/execute_docs/execute_docs_notebooks.py quick-start faq  # Multiple subdirs\n"
            "  python tools/execute_docs/execute_docs_notebooks.py user_guides/hyperparameter-tuning-and-lags-selection.ipynb\n"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "targets",
        nargs="*",
        default=None,
        help="Subdirectories or notebook files (relative to docs/) to execute. "
             "Examples: 'user_guides', 'user_guides/backtesting.ipynb'. "
             "If omitted, all notebooks under docs/ are executed.",
    )
    args = parser.parse_args()
    run_notebooks(targets=args.targets or None)
