name: ðŸž Bug report
description: Report a bug or unexpected behavior in skforecast
title: "[BUG]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to report a bug! Please fill out the sections below to help us understand and reproduce the issue.
    
  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "Steps/Code to reproduce the bug"
      description: |
        Please include a [minimal reproducible example](https://stackoverflow.com/help/mcve) so users can reproduce the error when running it. Be as succinct as possible, and do not depend on external data files.

        Being able to copy and paste code to reproduce an error is extremely helpful for us, and the issue will take longer to resolve if one is not included. If including a code example is not applicable for your report, enter "N/A" in the box.

        If the code is too long, feel free to put it in a public [gist](https://gist.github.com) and link it in the issue.
      placeholder: |
        ```python
        # Your code here
        ```
      value: |
        ```python
        # Paste your code here
        ```
      validations:
        required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior...
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please run the following code snippet and paste the output here.

        ```python
        from skforecast.utils import show_versions
        show_versions()
        ```
    validations:
      required: false
    
  - type: markdown
    attributes:
      value: >
        Thank you for reporting a bug and contributing to `skforecast`!
